### ISSUE TITLE
Functional Specification 

### ISSUE THREAD

**Issue by thomas-planchard** [algosup/2023-2024-project-2-x86-retrogaming-team-4#17]
**Issue Description:**
The user interface section of the functional specification is currently incomplete. Notably, the information related to quantization has been identified as technical and should be removed to enhance clarity for non-technical stakeholders. Additionally, the fruit sprites need adjustment, specifically replacing them with only the cherry sprite, as the other sprites are intended for bonus purposes. Furthermore, the section detailing the bonus aspect is currently missing and needs to be incorporated.

**Steps to Address:**
1. Complete the user interface section
2. Remove the technical information on quantization from the color section.
3. Replace the fruit sprites with only the cherry sprite in the relevant section.
4. Include a detailed section on the bonus aspect to complete the functional specification.

**Linked Document:**
[[Link to the Functional Specification Document]](https://github.com/algosup/2023-2024-project-2-x86-retrogaming-team-4/blob/main/documents/functional/functional-specifications.md)

**Comment by TechXplorerFR** [comment]
All the edits are being edited in the specification. This should be fixed by the end of the day.

**Comment by TechXplorerFR** [comment]
All the problems described here have been patched
