### ISSUE TITLE
Unauthorized Merge to Main Branch

### ISSUE THREAD

**Issue by thomas-planchard** [algosup/2023-2024-project-2-x86-retrogaming-team-4#21]
**Issue Summary:**
An unauthorized merge has been identified in the main branch. 

**Details:**
- **Branch Merged:** Github Issue]
- **Unauthorized Merger:** [Thomas Planchard]
- **Date and Time:** [November 19, 2023, 9:33 am]

**Expected Behavior:**
Changes to the main branch should only occur through authorized and documented procedures, ensuring proper review and validation.

**Recommendations:**
1. **Revert the Unauthorized Merge:**
   - Identify the commit hash of the unauthorized merge.
   - Execute a revert to undo the changes introduced by the unauthorized merge.

2. **Conduct a Review:**
   - Investigate how the unauthorized merge occurred.
   - Reinforce and communicate the project's branching and merging policies.

3. **Preventive Measures:**
   - Implement additional access controls to prevent unauthorized merges.

**Priority:** [Low]

**Comment by leo-chartier** [comment]
Settings have been modified to remove unnecessary permissions and additional protections have been added.
