### ISSUE TITLE
Technical Specification 

### ISSUE THREAD

**Issue by thomas-planchard** [algosup/2023-2024-project-2-x86-retrogaming-team-4#23]
Here is a list of all the mistakes in the Technical specification.
| Word# | Mistake Type | Explanation |
|-------|--------------|-------------|
| 19    | Spelling     | "Graphism" should be "Graphics" |
| 19    | Spelling     | "alterning" should be "alternating" |
| 19    | Spelling     | "mouse" should be "mouth" |
| 19    | Grammar      | "Pac-Man has also 2 different sprites" should be "Pac-Man also has 2 different sprites" |
| 41    | Spelling     | "alterning" should be "alternating" |
| 51    | Spelling     | "ned" should be "end" |
| 65    | Spelling     | "diferent" should be "different" |
| 69    | Spelling     | "mesaurements" should be "measurements" |
| 81    | Spelling     | "Patern" should be "Pattern" |
| 83    | Spelling     | "comportment" should be "behavior" |
| 87    | Grammar      | "between him and Blinky" should be "between him and Blinky's position" |
| 91    | Grammar      | "frightened anymore" should be "no longer frightened" |
| 93    | Spelling     | "colides" should be "collides" |
| 97    | Spelling     | "rendring" should be "rendering" |
| 99    | Spelling     | "depenging" should be "depending" |
| 111   | Spelling     | "Fuit" should be "Fruit" |
| 113   | Spelling     | "inputed" should be "input" |
| 121   | Grammar      | "all progression is lost" should be "all progress is lost" |
| 125   | Spelling     | "difirent" should be "different" |
| 129   | Spelling     | "compiled program" should be "compiled program's" |
| 129   | Grammar      | "executed on the same platform" should be "executed in the same environment" |
| 133   | Spelling     | "ot" should be "it" |
| 137   | Spelling     | "appearition" should be "appearance" |
| 143   | Spelling     | "level is finished" should be "level is completed" |
| 145   | Grammar      | "he goes back" should be "it goes back" |
| 147   | Spelling     | "ned" should be "end" |
| 155   | Grammar      | "level 256" should be "level 256," |
| 157   | Spelling     | "realisation" should be "realization" |
| 161   | Spelling     | "DOSBox's" should be "DOSBox" |
| 161   | Grammar      | "run on different platforms" should be "run on different operating systems" |
| 169   | Spelling     | "pallet" should be "palette" |
| 171   | Spelling     | "palette colour" should be "palette colors" |
| 173   | Spelling     | "delays" should be "Delays" |
| 173   | Grammar      | "extra hours" should be "additional time" |
| 175   | Grammar      | "the needed colours" should be "the required colors" |

**Comment by Malo-Archimbaud** [comment]
[technical-specifications.md](https://github.com/algosup/2023-2024-project-2-x86-retrogaming-team-4/files/13465479/technical-specifications.md)

**Comment by leo-chartier** [comment]
This I saw that could be improved on the document:
- Typos and formatting (line breaks)
- Too many functional details and not enough technical ones
- How should the sprite sheet and maze be encoded?
- How should the display be done?
- What is the algorithm to spawn fruits?
- What is the algorithm to move the ghosts?
- How should the collisions be dealt with in the code?
- The File Architecture section is not detailed enough.

Please add more code and diagrams to help understand how the code should work.

**Comment by thomas-planchard** [comment]
I saw a lot of typos and grammar mistakes. Here are few examples:
("each ghosts" line 70), ("two separate sprite"line 70), ("the ghost are" line 73), ("animation than before" line 73),("it's eyes remains" line 74) 
My advise to you is to install the grammarly extension on vscode and solve all your typos

**Comment by Malo-Archimbaud** [comment]
[technical-specifications.md](https://github.com/algosup/2023-2024-project-2-x86-retrogaming-team-4/files/13522962/technical-specifications.md)
