### ISSUE TITLE
Sprite error [2023/12/01]

### ISSUE THREAD

**Issue by MaximeAlgosup** [algosup/2023-2024-project-2-x86-retrogaming-team-4#35]
### Description

Sprite changes when sprite velocity is changed in "initialization" file

### Severity

3 - Medium

### Version

0.0

### System informations

Platform: Windows/Mac
DOSBox

### Steps taken

1. Change Blinky x velocity in "initialization" file
2. Run the game
3. Blinky is now a bell

### Expected result

Blinky supposed to be displayed as blinky

### Workaround or solution

I can come from the register used to save velocity which is probably crossing the register storing sprite

**Comment by benoitdekeyn-algosup** [comment]
The issue had been solved, so, all the sprites are well displayed, erased, and the velocity doesn't disturb anything.
