### ISSUE TITLE
Maze Erasure During Horizontal Ghost Movement [2023/12/04]

### ISSUE THREAD

**Issue by thomas-planchard** [algosup/2023-2024-project-2-x86-retrogaming-team-4#42]
### Description

We have identified a critical issue affecting the display of the maze in the game. When a ghost moves horizontally, it appears to erase parts of the maze

### Severity

2 - High

### Version

Dev Branch (Merge pull request #40 from algosup/maze_to_back_buffer_ben)

### System informations

Platform: MacOS Ventura: 13.4.1 
DOSBox 0.74.2

### Steps taken

Start a new game.
Observe the maze layout.
Observe Blinky
Note the sections of the maze that get erased during the ghost's horizontal movement.
<img width="643" alt="Screenshot 2023-12-04 at 15 59 55" src="https://github.com/algosup/2023-2024-project-2-x86-retrogaming-team-4/assets/91249646/08373e73-88bf-494e-8fd4-5825e1b95313">

### Expected result

The maze layout should remain intact during ghost movement.

**Comment by Malo-Archimbaud** [comment]
To be more precise, any entity (Pac-Man and ghosts) moving any other direction than down change the maze layout. Even going up change the maze.

**Comment by benoitdekeyn-algosup** [comment]
The issue has been solved and the ghosts don't rewrite wrongly the maze after they pass on pixels.
