### ISSUE TITLE
[Test Case 7] Pac-Man Collision [2023/12/08]

### ISSUE THREAD

**Issue by thomas-planchard** [algosup/2023-2024-project-2-x86-retrogaming-team-4#61]
### Description

It's sometimes a bit complicated to change direction because the space available for Pac-Man is too small. Pac-Man stops moving when the player presses the "UP" key when there is a wall above Pac-Man.

### Severity

3 - Medium

### Version

v0.2

### System informations

Platform: MACOS VENTURA
DOSBox 0.74-3

### Steps taken

1. Start the game
2. Move toward a intersection

### Expected result

The player must be able to negotiate intersections with ease. It must be fluid to enhance gameplay. 

### Workaround or solution

 I recommend implementing a key buffer to manage this.

**Comment by Malo-Archimbaud** [comment]
I have a beginning of something, but some it's not working for some corner yet

**Comment by MaximeAlgosup** [comment]
Closed with pull request #68
