### ISSUE TITLE
Eyes during freight time [2023/12/11]

### ISSUE THREAD

**Issue by leo-chartier** [algosup/2023-2024-project-2-x86-retrogaming-team-4#73]
### Description

Eyes display on ghosts during freight time when they should not.
![ghost eyes](https://github.com/algosup/2023-2024-project-2-x86-retrogaming-team-4/assets/91249751/092805c7-e5ba-45dd-925e-a65bb94d01a4)

### Severity

4 - Low

### Version

v0.3

### System informations

Platform: Windows/Mac
DOSBox Version

### Steps taken

Play the game and eat a Power Pellet

### Expected result

Have no additional eyes on ghosts
![ghost no eyes original](https://github.com/algosup/2023-2024-project-2-x86-retrogaming-team-4/assets/91249751/511676ec-5025-48d4-a51c-2a068d7cd3cf)
<img width="607" alt="ghost no eyes spritesheet" src="https://github.com/algosup/2023-2024-project-2-x86-retrogaming-team-4/assets/91249751/2ca3246e-b444-4e61-b0f6-db3bf23a9038">

### Workaround or solution

When rendering a ghost, additionally to changing the sprite's appearance, skip rendering the eyes.

**Comment by benoitdekeyn-algosup** [comment]
While fixing all the animations of the sprites, I also rewoved the eyes of the frightened ghosts.
