### ISSUE TITLE
Power pellet eating after death [2023/12/16]

### ISSUE THREAD

**Issue by MaximeTAlgosup** [algosup/2023-2024-project-2-x86-retrogaming-team-4#78]
### Description

After the death of Pac-Man, you can eat again the power pellet even if they are not visible on the map. I assume that it does the same with the pellet and the score.

### Severity

2 - High

### Version

v0.3

### System informations

Platform: Windows/Mac
DOSBox Version

### Steps taken

I wanted to eat a pellet near a previous power pellet and the fright time started.

### Expected result

We shouldn't eat power pellets when they are not displayed.

**Comment by benoitdekeyn-algosup** [comment]
The reset point in the main file was at a wrong step of the initialization.
When the game was reset, we called the function which clone the original maze model into the background buffer, whereas we wanted to stay on the modified maze model buffer.
